# Generated by Django 3.1.1 on 2020-10-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20201024_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='area',
            new_name='area_hectares',
        ),
    ]
